apiVersion: apps/v1
kind: Deployment
metadata:
  name: argonet-deployment
spec:
  selector:
    matchLabels:
      app: argonet-app
  replicas: 3
  template:
    metadata:
      labels:
        app: argonet-app
    spec:
      containers:
        - name: globi-app
          image: kasacka/argonet:1.1
          ports:
            - containerPort: 3000