apiVersion: v1
kind: Service
metadata:
  name: argonet-service
spec:
  selector:
    app: argonet-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32500